Model database setup
mirasoldavila13/NeighborhoodAid pull request #22
Opened 2024-10-01 04:58 UTC by PandaKao

need to install postGIS to use database also redo database schema.sql

2024-10-01 05:17 UTC, mirasoldavila13 requested changes
Thank you for your hard work on this! I’ve reviewed the changes, and there are just a few adjustments needed before we can merge:

  1.  Revert changes to .github/ISSUE_TEMPLATE/user-story.md: We should keep this file consistent with our original template.

  2.  Remove client/package-lock.json, server/package-lock.json, and package-lock.json from the push: The versions here have fewer dependencies than what's in the main branch, and merging them could cause issues with our setup.

  3.  Uncomment server/config/connection.js: This file is necessary for Sequelize, and our deployment platform (Render) requires it to be in the config folder.

Once these changes are made, we’ll be ready to proceed with the merge. Let me know if you need any assistance!

2024-10-01 16:44 UTC, PandaKao commented
Couldn't find where our user-story is, main doesn't have it. removed all package-locked.json as well as copied the package.json directly from main. Reinstated server/config/connection.js.

2024-10-01 23:44 UTC, mirasoldavila13 commented
I was checking out your index.js and noticed it's a bit different from what we have in the main branch. We're using Sequelize ORM to automatically load models and set up relationships, so we don't need to manually import them. It helps keep things flexible as we add more models.

Could you try pulling the latest from the main branch and adjust your file to match the dynamic setup we're using? Let me know if you need a hand with anything!

Thanks so much!

2024-10-02 01:08 UTC, mirasoldavila13 approved these changes
Looks great!

2024-10-02 01:08 UTC, mirasoldavila13 commented on server/models/index.js
@PandaKao  I was checking out your index.js and noticed it's a bit different from what we have in the main branch. We're using Sequelize ORM to automatically load models and set up relationships, so we don't need to manually import them. It helps keep things flexible as we add more models.

Could you try pulling the latest from the main branch and adjust your file to match the dynamic setup we're using? Let me know if you need a hand with anything! Here is the link : https://github.com/mirasoldavila13/NeighborhoodAid/blob/main/models/index.js

2024-10-02 01:08 UTC, merged