Issue form
mirasoldavila13/NeighborhoodAid pull request #25
Opened 2024-10-01 23:52 UTC by thepeoplesengineer

Pushing to issue_form branch, you can delete the other IssueFormCreation branch (was a test).

Made changes to input fields to reflect Issue #3 user story first task. Updated backend to reflect.

2024-10-02 00:30 UTC, mirasoldavila13 requested changes
Great job on the IssueForm.tsx and ESLint configuration! I’ve left some specific comments in the code for areas where we can make tweaks:

    File Upload Handling: I’ve suggested using FormData for file uploads to handle the picture field properly.
    Status Dropdown: I noticed you’ve hardcoded the status as "reported" for now, which makes sense as a placeholder. When you're ready, you can switch this to a dropdown as per the user story.
    Checkbox Handling: I suggested refactoring the checkbox logic into your existing handleChange function for consistency and cleaner code.
    ESLint Configuration: I also noted a few differences in the ESLint setup—since the project uses TypeScript, it should target **/*.ts and **/*.tsx instead of JavaScript/JSX files.

Let me know if you need help with any of these updates. Thanks again for the hard work!

2024-10-02 16:21 UTC, thepeoplesengineer commented
Okay got it! Thanks for the feedback!

On Tue, Oct 1, 2024 at 5:30 PM Mirasol Davila ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Great job on the IssueForm.tsx and ESLint configuration! I’ve left some
> specific comments in the code for areas where we can make tweaks:
>
> File Upload Handling: I’ve suggested using FormData for file uploads to handle the picture field properly.
> Status Dropdown: I noticed you’ve hardcoded the status as "reported" for now, which makes sense as a placeholder. When you're ready, you can switch this to a dropdown as per the user story.
> Checkbox Handling: I suggested refactoring the checkbox logic into your existing handleChange function for consistency and cleaner code.
> ESLint Configuration: I also noted a few differences in the ESLint setup—since the project uses TypeScript, it should target **/*.ts and **/*.tsx instead of JavaScript/JSX files.
>
> Let me know if you need help with any of these updates. Thanks again for
> the hard work!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mirasoldavila13/NeighborhoodAid/pull/25#pullrequestreview-2341663580>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BGPGYV75UDRGR4XAVKZYDZTZZM5CFAVCNFSM6AAAAABPGTHRN2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNBRGY3DGNJYGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-04 18:09 UTC, mirasoldavila13 requested changes
Hey @thepeoplesengineer ,

Great work on the project so far! I really appreciate all the effort you've put into it. I have a few suggestions and am requesting some changes that I think will help align everything a bit more smoothly with the overall project goals:

 1.  Change LocationSelector from a Component to a Page: Since this feature is focused on making community reports and won’t need to be reused elsewhere, it would make sense to change it from a component to a dedicated page. This will help keep everything related to the report submission in one place and make it easier to manage. A name like CommunityReport.tsx would be a great fit to reflect its purpose and help with clarity.

 2.   Switch from Hardcoded Location: I noticed the default lat/lng is set to London. I’ve been using the OpenWeather API, OpenWeather Geolocation API, and OpenStreetMap API in my part of the project to dynamically detect the user's actual location and integrate it with the map, making it more personalized. Last night, I created a reusable component that handles this functionality for consistency. I’ll push it later today so you can merge it and incorporate it into your part of the project.

 3.   Success/Error Handling for Report Creation: For user feedback when they submit a report, using Modal.tsx to display success or error messages would be really helpful. This would give users instant feedback, like “Report created successfully!” or a relevant error message if something goes wrong. I think this would greatly improve the overall experience for users.

4.    Restore the Previous Route and Create a New One for CommunityReport: I noticed that the server/routes/issueRoutes.js file was updated with changes for the CommunityReport feature, but this removed the existing functionality for weather-based issue reporting, which is tied to ReportPage.tsx. The original route fetched the user’s location using the OpenWeather Geolocation API, integrating it with the OpenWeather API and OpenStreetMap API to display the current weather for the selected location. Since both features are important, I recommend restoring the original route for the weather-based reporting and creating a separate route for the CommunityReport. This way, we can ensure both features work seamlessly together.

Please feel free to reach out if you need any help with these changes, and thanks again for all your hard work! I’m excited to see how everything comes together.

Best,
@mirasoldavila13

2024-10-05 21:12 UTC, mirasoldavila13 requested changes
Hi @thepeoplesengineer ,

I hope you’re doing well! I wanted to reach out and suggest a few updates to keep everything aligned with the project requirements:

    Revert issue-authority-seed.js: This file is specific to GitHub Issue 3 (authority reports), and since your work focuses on Issue 7 (community reports), it would be best to revert this file to its original version, which includes the necessary function call for seeding the authority data.

    Remove Weather and Rename issueRoutes.js: In Issue 7, weather functionality is not required for community reports. Could you please remove the weather-related code from server/routes/issueRoutes.js? The weather functionality is specific to Issue 3 and is handled in ReportAuthorityRoute.js. To keep everything organized, could you also rename issueRoutes.js to CommunityIssueRoutes.js and update the model and route names to include "community"? This will help avoid any confusion with the authority routes.

    Rename reportCommunity.js Model: The structure of the model looks solid! To avoid confusion with other models, like those for authority reports, could we rename it to CommunityIssue? This will help make its purpose more clear and avoid conflicts in the future.

    Revert Changes to reportAuthority.js: This file is connected to Issue 3 (ReportPage.tsx). Since your work doesn’t involve the backend or creating routes for this feature, it would be best to revert any changes. If you're interested in working on the backend for Issue 7, we can set up a separate route for CommunityReport.tsx.

    Revert `ReportOptionsPage.tsx: The changes made here are affecting Issue 4, which has already been implemented. Could we please revert this file to the version in the main branch to maintain the original structure?

    CommunityReportPage.tsx: According to Issue 7, weather functionality isn’t necessary for this page. Could you remove the weather-related code to stay focused on the requirements? This will help avoid any impact on other areas, like Issue 3 and Dashboard.tsx.

    Weather Feature: I noticed some changes to the weather feature that impact Issue 3 and how the weather data displays in Dashboard.tsx. Could we revert those changes back to the original structure so everything remains consistent?

    MapWithAddress.tsx: To maintain consistency with the main branch, please revert back to the original structure, including the marker icon configuration, string formatting, and TileLayer attribution.

    App.tsx: For CommunityReportPage.tsx, could we please revert to the original route (/dashboard/report/community) as per the main branch? This will help keep things consistent.

Lastly, I noticed you uploaded some pictures of a pothole—those could go into the assets folder. It also looks like there was a personal photo included—perhaps by accident? If so, no worries!

Thanks so much for your dedication and hard work on this project! Let me know if you need any help or have any questions.

2024-10-05 21:12 UTC, mirasoldavila13 commented on client/src/App.tsx
Hi @thepeoplesengineer ,

I wanted to point out that for client/src/App.tsx, we need to revert to using CommunityReportPage.tsx as per the original setup in the main branch. The route for the Community Report feature should remain /dashboard/report/community to ensure consistency across the project.

This alignment with the main branch will help avoid any conflicts moving forward. Please make the necessary adjustments to reflect this.

Let me know if you have any questions, and thank you for your effort on this!

Best,
@mirasoldavila13

2024-10-05 21:12 UTC, mirasoldavila13 commented on client/src/components/MapWithAddress.tsx
Hi @thepeoplesengineer ,

I’ve reviewed the recent changes to the MapWithAddress.tsx file and noticed some structural differences from the original setup. To maintain consistency and avoid potential issues, I’d like to request that we revert back to the original structure.

Specifically, please:

    Revert to the original marker icon configuration (including the correct shadowSize property).
    Ensure consistent string formatting (using single quotes throughout).
    Correct the TileLayer attribution by removing the extra comma at the end of the string.

These changes will help ensure everything is aligned with the main branch and maintain the project’s overall structure. Let me know if you need any clarification or help with the reversion.

Thanks for your understanding!

Best,
@mirasoldavila13

2024-10-05 21:12 UTC, mirasoldavila13 commented on client/src/components/Weather.tsx
Hi @thepeoplesengineer ,

I noticed that some changes were made to the weather feature, but I just wanted to clarify that GitHub Issue 7 doesn’t require adjustments to the weather functionality. These changes are also affecting GitHub Issue 3 and how the weather displays in Dashboard.tsx, so it would be best to revert those updates to the original structure and UI.

If you could focus on the tasks specific to Issue 7 and revert the weather changes, that would help keep everything aligned with the project requirements. Let me know if you need any assistance with this!

Thanks for your hard work, and I appreciate your understanding.

Best,
@mirasoldavila13

2024-10-05 21:12 UTC, mirasoldavila13 commented on client/src/pages/CommunityReportPage.tsx
Hi @thepeoplesengineer ,

I hope you’re doing well! I wanted to touch base about the CommunityReportPage.tsx. According to the requirements for GitHub Issue 7, the goal is to create a form for users to report community issues by providing a description, selecting a location, and choosing a status. Since the issue doesn’t mention weather functionality, it’s not necessary for this page.

To stay aligned with the task, could you please remove the weather-related code? This will help keep everything focused on the requirements and avoid any unintended impact on other areas, such as GitHub Issue 3 and the Dashboard.tsx.

If you have any questions or need a hand, feel free to reach out. I really appreciate your hard work and attention to detail!

2024-10-05 21:12 UTC, mirasoldavila13 commented on client/src/pages/ReportOptionsPage.tsx
Hi @thepeoplesengineer ,

I noticed that the changes to client/src/pages/ReportOptionsPage.tsx are impacting GitHub Issue 4, which was already implemented. Could you please revert the file back to the version in the main branch? We need the original structure from GitHub Issue 4 to stay intact for the project.

Let me know if you have any questions or need any help with this!

2024-10-05 21:12 UTC, mirasoldavila13 commented on server/models/reportAuthority.js
Hi @thepeoplesengineer ,

I hope you're doing well! I noticed some changes were made to reportAuthority.js, which is for ReportPage.tsx and connected to GitHub Issue 3 (authority reports). Since your part doesn’t involve working on the backend or creating a route, it would be best to revert those changes.

If you’re interested in working on the backend for Issue 7 related to CommunityReport.tsx, that would be awesome! In that case, CommunityReport.tsx would need its own route because it serves a different purpose from ReportPage.tsx (which is for reporting to authorities). Each needs its own dedicated route to avoid any conflicts and to keep the functionality clear and separate.

Let me know if you’re interested in exploring that, or if you have any questions—I’d be happy to assist!

Thanks again for your understanding, and I appreciate all your hard work.

2024-10-05 21:12 UTC, mirasoldavila13 commented on server/models/reportCommunity.js
Hi @thepeoplesengineer ,

I hope you’re doing well! I took a look at the model in reportCommunity.js, and it looks great! The structure is solid, and everything seems to be on track for handling community reports effectively.

One small suggestion: to keep things clearer and avoid any potential confusion with other models (like the one for authority reports), could you rename it to something more specific, like CommunityIssue?

To ensure there are no conflicts with other parts of the project, you can:

    Check the database migrations and schema to make sure there are no conflicting table names.
    Verify that there aren’t duplicate models in the same Sequelize instance.
    Review the routes and endpoints to make sure each model has its own distinct path and functionality.

Let me know if you have any questions or need any assistance with the renaming process—it’s really coming together!

Thanks again for your hard work, I appreciate it.

2024-10-05 21:12 UTC, mirasoldavila13 commented on server/routes/ReportAuthorityRoute.js
Hi @thepeoplesengineer ,

I hope you're doing well! I wanted to suggest a small but important update in server/routes/issueRoutes.js. To help keep things clear and organized, it would be great to rename the Issue import to CommunityIssue, since this route specifically handles community reports. By using a more descriptive name, we can avoid confusion and ensure that the purpose of the model is immediately clear, especially as the project grows.

If you need any help with the change, feel free to reach out!

Thanks again for your hard work—I really appreciate it!

2024-10-05 21:12 UTC, mirasoldavila13 commented on server/routes/issueRoutes.js
Hi @thepeoplesengineer ,

I hope you're doing well! I noticed that the route for community issues in server/routes/issueRoutes.js includes weather data. Just to clarify, the weather functionality is specific to GitHub Issue 3, which is for authority reports, and should only be present in ReportAuthorityRoute.js.

Additionally, to keep the naming clear and organized, it would be helpful to rename the file to CommunityIssueRoutes.js and update the model and route names to include "community." This will help differentiate it from the authority routes and avoid any confusion.

Could you please make these updates? Let me know if you need any help or have any questions!

Thanks again for your hard work—I really appreciate it!

2024-10-05 21:12 UTC, mirasoldavila13 commented on server/seeds/issue-authority-seed.js
Hi @thepeoplesengineer ,

I hope you're doing well! I noticed some changes were made to issue-authority-seed.js. Since this file is specifically for GitHub Issue 3 (authority reports), it doesn’t align with the scope of GitHub Issue 7, which focuses on community reports. To maintain clarity and purpose, could we please revert this file to the original version? The original also includes the necessary function call for the seed data to be inserted properly.

If you have any questions or would like further clarification, feel free to reach out! I appreciate all your hard work and dedication to the project.

2024-10-07 02:30 UTC, merged